runtime: nodejs18

instance_class: F1

handlers:
  - url: /static
    static_dir: build/static

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: build/index.html
    upload: build/index.html
